on:
  push:
    branches: [main]
jobs:
  publish_to_docker_pr_event:
    uses: MAALSI23-BLOC-3/UserManagementMS/.github/workflows/cd_docker_img.yml@develop
    with:
      name: 'productsms'
    secrets: inherit
